### ISSUE TITLE
readme中的图片

### ISSUE THREAD

**Issue by tg-Flipped** [chenluda/CVPR2023-download#1]
![image](https://github.com/chenluda/CVPR2023-download/assets/49100695/584607a2-fa33-4797-9738-b02f86fbc7dd)
请问这张图片展示的效果是运行app.py得到的吗？

**Comment by dengh01** [comment]
是的 通过查询展示的 template有个index.html

**Comment by chenluda** [comment]
感谢 @dengh01 的回复。

是的，运行 app.py 可以得到图片展示的效果，但前提是需要构建一个数据库，sql 文件应该可以在库里找到。 @tg-Flipped

**Comment by dengh01** [comment]
@chenluda 不客气 项目也有帮助到我。
感觉可以再改良一版本 抽离链接以时间为传入查询粒度，做一个类似知识图谱存储的结构 如sci-hub这类，把手工标注加星筛选也作为一项功能 可能会更好用点。
